class ExecuteSql < ActiveRecord::Migration
  
  #  Document   : 008_execute_sql.rb
  #  Updated on : October 27, 2008, 1:16 PM
  #  Author     : Jared, Niki, Shane
  #  Description: Populate the database with development testing data
  
  def self.up
    #id,          depreciated, q_data,        master_id,              created_at, updated_at
    #Question ID, depreciated (for javascript issues), question data, master id (used when there is a passage and more than 1 question following it), date created, last update of data
    #Check the database for more information
    execute "insert into questions values (1, 0, '#{File.open('public/xml/exam_end.xml').read}',null,'End', null, null);"
    execute "insert into questions values (2, 0, '#{File.open('public/xml/new_exam.xml').read}',null,'New', null, null);"
    #execute "insert into questions values (2, 0, '#{File.open('public/xml/test.xml').read}',null,'Numeracy', null, null);"
    #execute "insert into questions values (3, 0, '#{File.open('public/xml/test2.xml').read}',null,'Literacy', null, null);"
    #execute "insert into questions values (4, 0, '#{File.open('public/xml/test3.xml').read}',null,'Numeracy', null, null);"
    #execute "insert into questions values (5, 0, '#{File.open('public/xml/test4.xml').read}',null,'Literacy', null, null);"
    #execute "insert into questions values (6, 0, '#{File.open('public/xml/test5.xml').read}',null,'Literacy', null, null);"
    #execute "insert into questions values (7, 0, '#{File.open('public/xml/test6.xml').read}',null,'Literacy', null, null);"
    #execute "insert into questions values (8, 0, '#{File.open('public/xml/test7.xml').read}',null,'Literacy', null, null);"
    #execute "insert into questions values (9, 0, '#{File.open('public/xml/test8.xml').read}',null,'Literacy', null, null);"
    #execute "insert into questions values (10, 0, '#{File.open('public/xml/test9.xml').read}',null,'Literacy', null, null);"
    #execute "insert into questions values (11, 0, '#{File.open('public/xml/test10.xml').read}',null,'Literacy', null, null);"
    #execute "insert into questions values (12, 0, '#{File.open('public/xml/test_single.xml').read}',null,'Literacy', null, null);"
    #execute "insert into questions values (13, 0, '#{File.open('public/xml/test11.xml').read}',null,'Numeracy', null, null);"
    #execute "insert into questions values (14, 0, '#{File.open('public/xml/test12.xml').read}',null,'Literacy', null, null);"
    #execute "insert into questions values (15, 0, '#{File.open('public/xml/test13.xml').read}',null,'Literacy', null, null);"
    #execute "insert into questions values (16, 0, '#{File.open('public/xml/master.xml').read}',null,'Decimal', null, null);"
    #execute "insert into questions values (17, 0, '#{File.open('public/xml/sub1.xml').read}',16,'Literacy', null, null);"
    #execute "insert into questions values (18, 0, '#{File.open('public/xml/sub2.xml').read}',16, 'Literacy',null, null);"
    execute "insert into questions values (3, 0, '#{File.open('public/xml/e1JobsInvolvingShiftworkPassage.xml').read}',null,'Literacy', null, null);"
    execute "insert into questions values (4, 0, '#{File.open('public/xml/e1q1Shiftwork.xml').read}',3,'Literacy', null, null);"
    execute "insert into questions values (5, 0, '#{File.open('public/xml/e1q2Shiftwork.xml').read}',3,'Literacy', null, null);"
    execute "insert into questions values (6, 0, '#{File.open('public/xml/e1q3Shiftwork.xml').read}',3,'Literacy', null, null);"
    execute "insert into questions values (7, 0, '#{File.open('public/xml/e1q4Shiftwork.xml').read}',3,'Literacy', null, null);"
    execute "insert into questions values (8, 0, '#{File.open('public/xml/e1q5Shiftwork.xml').read}',3,'Literacy', null, null);"
    execute "insert into questions values (9, 0, '#{File.open('public/xml/e1q6Shiftwork.xml').read}',3,'Literacy', null, null);"
    execute "insert into questions values (10, 0, '#{File.open('public/xml/e1q7Shiftwork.xml').read}',3,'Literacy', null, null);"
    execute "insert into questions values (11, 0, '#{File.open('public/xml/e1q8Shiftwork.xml').read}',null,'Literacy', null, null);"
    execute "insert into questions values (12, 0, '#{File.open('public/xml/e1q9Shiftwork.xml').read}',null,'Literacy', null, null);"
    execute "insert into questions values (13, 0, '#{File.open('public/xml/e2TreatingBurnsPassage.xml').read}',null,'Literacy', null, null);"
    execute "insert into questions values (14, 0, '#{File.open('public/xml/e2q1TreatingBurns.xml').read}',13,'Literacy', null, null);"
    execute "insert into questions values (15, 0, '#{File.open('public/xml/e2q2TreatingBurns.xml').read}',13,'Literacy', null, null);"
    execute "insert into questions values (16, 0, '#{File.open('public/xml/e2q3TreatingBurns.xml').read}',13,'Literacy', null, null);"
    execute "insert into questions values (17, 0, '#{File.open('public/xml/e2q4TreatingBurns.xml').read}',13,'Literacy', null, null);"
    execute "insert into questions values (18, 0, '#{File.open('public/xml/e2q1Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (19, 0, '#{File.open('public/xml/e2q2Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (20, 0, '#{File.open('public/xml/e2q3Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (21, 0, '#{File.open('public/xml/e2q4Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (22, 0, '#{File.open('public/xml/e2q5Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (23, 0, '#{File.open('public/xml/e2q6Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (24, 0, '#{File.open('public/xml/e2q7Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (25, 0, '#{File.open('public/xml/e2q8Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (26, 0, '#{File.open('public/xml/e2q9Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (27, 0, '#{File.open('public/xml/e2q10Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (28, 0, '#{File.open('public/xml/e2q11Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (29, 0, '#{File.open('public/xml/e2q12Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (30, 0, '#{File.open('public/xml/e2q13Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (31, 0, '#{File.open('public/xml/e2q14Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (32, 0, '#{File.open('public/xml/e2q15Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (33, 0, '#{File.open('public/xml/e2q16Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (34, 0, '#{File.open('public/xml/e2q17Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (35, 0, '#{File.open('public/xml/e2q18Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (36, 0, '#{File.open('public/xml/e2q19Numeracy.xml').read}',null,'Numeracy', null, null);"
    execute "insert into questions values (37, 0, '#{File.open('public/xml/e3DetergentPassage.xml').read}',null,'Literacy', null, null);"
    execute "insert into questions values (38, 0, '#{File.open('public/xml/e3q1Detergent.xml').read}',37,'Literacy', null, null);"
    execute "insert into questions values (39, 0, '#{File.open('public/xml/e3q2Detergent.xml').read}',37,'Literacy', null, null);"
    execute "insert into questions values (40, 0, '#{File.open('public/xml/e3q3Detergent.xml').read}',37,'Literacy', null, null);"
    execute "insert into questions values (41, 0, '#{File.open('public/xml/e3q4Detergent.xml').read}',37,'Literacy', null, null);"
    execute "insert into questions values (42, 0, '#{File.open('public/xml/e3CulinaryPassage.xml').read}',null,'Literacy', null, null);"
    execute "insert into questions values (43, 0, '#{File.open('public/xml/e3q1Culinary.xml').read}',42,'Literacy', null, null);"
    execute "insert into questions values (44, 0, '#{File.open('public/xml/e3q2Culinary.xml').read}',42,'Literacy', null, null);"
    execute "insert into questions values (45, 0, '#{File.open('public/xml/e3q3Culinary.xml').read}',42,'Literacy', null, null);"
    execute "insert into questions values (46, 0, '#{File.open('public/xml/e3q4Culinary.xml').read}',42,'Literacy', null, null);"
    execute "insert into questions values (47, 0, '#{File.open('public/xml/e3q5Culinary.xml').read}',42,'Literacy', null, null);"
    execute "insert into questions values (48, 0, '#{File.open('public/xml/e3q6Culinary.xml').read}',42,'Literacy', null, null);"
  
    #id,      name,             created_by,   results_viewable,         status,         skippable
    #Exam ID, name of the exam, id of teacher, results are viewable(0= invisible, 1= visible), status of exam (0= disabled, 1= enabled) , exam is skippable (0= not skippable, 1= skippable)
    #execute "insert into exams values (1, 'Random Test', 1, 1, 1, 1,'Numeracy', null, null);"
    
    #id               , exam_id,            question_id,      position, created_at, updated_at
    #Exam Question ID, belongs to exam (ID), question ID insert, question's queue number,date created, date updated
    #execute "insert into exam_questions values (1,1,1,0,  null, null);"
    #execute "insert into exam_questions values (2,1,2,1,  null, null);"
    #execute "insert into exam_questions values (3,1,3,2,  null, null);"
    #execute "insert into exam_questions values (4,1,4,3,  null, null);"
    #execute "insert into exam_questions values (5,1,5,4,  null, null);"
    #execute "insert into exam_questions values (6,1,6,5,  null, null);"
    #execute "insert into exam_questions values (7,1,7,6,  null, null);"


    #execute "insert into exams values (2, 'Quite random Test', 1, 1, 1, 1,'Alphabetical', null, null);"
    #execute "insert into exam_questions values (8,2,1,0,  null, null);"
    #execute "insert into exam_questions values (9,2,2,1,  null, null);"
    #execute "insert into exam_questions values (10,2,3,2,  null, null);"
    #execute "insert into exam_questions values (11,2,4,3,  null, null);"
    #execute "insert into exam_questions values (12,2,5,4,  null, null);"
    #execute "insert into exam_questions values (13,2,6,5,  null, null);"
    #execute "insert into exam_questions values (14,2,7,6,  null, null);"
    #execute "insert into exam_questions values (15,2,8,7,  null, null);"
    #execute "insert into exam_questions values (16,2,9,8,  null, null);"
    #execute "insert into exam_questions values (17,2,10,9,  null, null);"
    #execute "insert into exam_questions values (18,2,11,10,  null, null);"
    #execute "insert into exam_questions values (19,2,12,11,  null, null);"
    #execute "insert into exam_questions values (20,2,13,12,  null, null);"
    #execute "insert into exam_questions values (21,2,14,13,  null, null);"
    #execute "insert into exam_questions values (22,2,15,14,  null, null);"


    #execute "insert into exams values (3, 'aaaaaaaa', 1, 1, 1, 1,'Alphabetical', null, null);"
    #execute "insert into exam_questions values (23,3,1,0,  null, null);"
    #execute "insert into exam_questions values (24,3,3,1,  null, null);"
    #execute "insert into exam_questions values (25,3,4,2,  null, null);"
    #execute "insert into exam_questions values (26,3,5,3,  null, null);"


    #execute "insert into exams values (4, 'blah', 1, 1, 1, 1,'Alphabetical', null, null);"
    #execute "insert into exam_questions values (27,4,1,0,  null, null);"
    #execute "insert into exam_questions values (28,4,3,1,  null, null);"
    #execute "insert into exam_questions values (29,4,4,2,  null, null);"
    #execute "insert into exam_questions values (30,4,5,3,  null, null);"
    #execute "insert into exam_questions values (31,4,6,4,  null, null);"
    #execute "insert into exam_questions values (32,4,7,5,  null, null);"
    #execute "insert into exam_questions values (33,4,8,6,  null, null);"
    #execute "insert into exam_questions values (34,4,9,7,  null, null);"
    #execute "insert into exam_questions values (35,4,10,8,  null, null);"


    execute "insert into exams values (1, 'Jobs Involving Shiftwork', 1, 1, 1, 1,'Literacy', null, null);"
    execute "insert into exam_questions values (1,1,1,0,  null, null);"
    execute "insert into exam_questions values (2,1,3,1,  null, null);"
    execute "insert into exam_questions values (3,1,4,2,  null, null);"
    execute "insert into exam_questions values (4,1,5,3,  null, null);"
    execute "insert into exam_questions values (5,1,6,4,  null, null);"
    execute "insert into exam_questions values (6,1,7,5,  null, null);"
    execute "insert into exam_questions values (7,1,8,6,  null, null);"
    execute "insert into exam_questions values (8,1,9,7,  null, null);"
    execute "insert into exam_questions values (9,1,10,8,  null, null);"
    execute "insert into exam_questions values (10,1,11,9,  null, null);"
    execute "insert into exam_questions values (11,1,12,10,  null, null);"


    execute "insert into exams values (2, 'Treating Burns', 1, 1, 1, 1,'Literacy', null, null);"
    execute "insert into exam_questions values (12,2,1,0,  null, null);"
    execute "insert into exam_questions values (13,2,13,1,  null, null);"
    execute "insert into exam_questions values (14,2,14,2,  null, null);"
    execute "insert into exam_questions values (15,2,15,3,  null, null);"
    execute "insert into exam_questions values (16,2,16,4,  null, null);"
    execute "insert into exam_questions values (17,2,17,5,  null, null);"
    execute "insert into exam_questions values (18,2,18,6,  null, null);"
    execute "insert into exam_questions values (19,2,19,7,  null, null);"
    execute "insert into exam_questions values (20,2,20,8,  null, null);"
    execute "insert into exam_questions values (21,2,21,9,  null, null);"
    execute "insert into exam_questions values (22,2,22,10,  null, null);"
    execute "insert into exam_questions values (23,2,23,11,  null, null);"
    execute "insert into exam_questions values (24,2,24,12,  null, null);"
    execute "insert into exam_questions values (25,2,25,13,  null, null);"
    execute "insert into exam_questions values (26,2,26,14,  null, null);"
    execute "insert into exam_questions values (27,2,27,15,  null, null);"
    execute "insert into exam_questions values (28,2,28,16,  null, null);"
    execute "insert into exam_questions values (29,2,29,17,  null, null);"
    execute "insert into exam_questions values (30,2,30,18,  null, null);"
    execute "insert into exam_questions values (31,2,31,19,  null, null);"
    execute "insert into exam_questions values (32,2,32,20,  null, null);"
    execute "insert into exam_questions values (33,2,33,21,  null, null);"
    execute "insert into exam_questions values (34,2,34,22,  null, null);"
    execute "insert into exam_questions values (35,2,35,23,  null, null);"
    execute "insert into exam_questions values (36,2,36,24,  null, null);"


    execute "insert into exams values (3, 'Numeracy only', 1, 1, 1, 1,'Numeracy', null, null);"
    execute "insert into exam_questions values (37,3,1,0,  null, null);"
    execute "insert into exam_questions values (38,3,18,1,  null, null);"
    execute "insert into exam_questions values (39,3,19,2,  null, null);"
    execute "insert into exam_questions values (40,3,20,3,  null, null);"
    execute "insert into exam_questions values (41,3,21,4,  null, null);"
    execute "insert into exam_questions values (42,3,22,5,  null, null);"
    execute "insert into exam_questions values (43,3,23,6,  null, null);"
    execute "insert into exam_questions values (44,3,24,7,  null, null);"
    execute "insert into exam_questions values (45,3,25,8,  null, null);"
    execute "insert into exam_questions values (46,3,26,9,  null, null);"
    execute "insert into exam_questions values (47,3,27,10,  null, null);"
    execute "insert into exam_questions values (48,3,28,11,  null, null);"
    execute "insert into exam_questions values (49,3,29,12,  null, null);"
    execute "insert into exam_questions values (50,3,30,13,  null, null);"
    execute "insert into exam_questions values (51,3,31,14,  null, null);"
    execute "insert into exam_questions values (52,3,32,15,  null, null);"
    execute "insert into exam_questions values (53,3,33,16,  null, null);"
    execute "insert into exam_questions values (54,3,34,17,  null, null);"
    execute "insert into exam_questions values (55,3,35,18,  null, null);"
    execute "insert into exam_questions values (56,3,36,19,  null, null);"


    execute "insert into exams values (4, 'Culinary', 1, 1, 1, 1,'Literacy', null, null);"
    execute "insert into exam_questions values (57,4,1,0,  null, null);"
    execute "insert into exam_questions values (58,4,37,1,  null, null);"
    execute "insert into exam_questions values (59,4,38,2,  null, null);"
    execute "insert into exam_questions values (60,4,39,3,  null, null);"
    execute "insert into exam_questions values (61,4,40,4,  null, null);"
    execute "insert into exam_questions values (62,4,41,5,  null, null);"
    execute "insert into exam_questions values (63,4,42,6,  null, null);"
    execute "insert into exam_questions values (64,4,43,7,  null, null);"
    execute "insert into exam_questions values (65,4,44,8,  null, null);"
    execute "insert into exam_questions values (66,4,45,9,  null, null);"
    execute "insert into exam_questions values (67,4,46,10,  null, null);"
    execute "insert into exam_questions values (68,4,47,11,  null, null);"
    execute "insert into exam_questions values (69,4,48,12,  null, null);"

    execute "insert into admins values (1, 'Administrator', 'Admin', 1, 'fc308d97f4ae2976271a11eef8fd784f722e1d02', '227060.6446051061556843', null, null);"
    #execute "insert into teachers values (1, 'admin', null, null, 1, 1, 'ad1dbe80f0154da51cbe3171ce6b9c2b58f7301c','1925320.42069743540134785', null, null);"
    #execute "insert into teachers values (2, 'teacher', null, null, 1, 1, '2851bfb31ccc5a7a261567646e45126ab5e6cfd1','1947000.8642262405039629', null, null);"


  end

  def self.down
  end
end